version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: mysite-postgres
    environment:
      POSTGRES_DB: mysite_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mysite-network
    ports:
      - "5432:5432"

  django:
    build:
      context: .
    container_name: mysite-django
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Internal port, exposed for Gunicorn
    depends_on:
      - postgres
    networks:
      - mysite-network
    environment:
      POSTGRES_DB: mysite_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  nginx:
    image: nginx:latest
    container_name: mysite-nginx
    depends_on:
      - django
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx config
    ports:
      - "80:80"  # External port, exposed for Nginx
    networks:
      - mysite-network

volumes:
  postgres_data:

networks:
  mysite-network:
